{{- if .Values.global.includeUnleash }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-unleash-db
  labels:
    app.kubernetes.io/name: unleash-db
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: unleash-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: unleash-db
    spec:
      containers:
        - name: postgresql
          image: {{ .Values.infra.unleash.db.image }}
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-unleash-secret
                  key: postgres-db-name
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-unleash-secret
                  key: postgres-username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-unleash-secret
                  key: postgres-password
          readinessProbe:
            exec:
              command: ["/bin/sh", "-c", "pg_isready -U $POSTGRESQL_USER -d $POSTGRESQL_DATABASE"]
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/pgsql/data
      volumes:
        - name: db-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-unleash-db
  labels:
    app.kubernetes.io/name: unleash-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: unleash-db
{{- end }}