apiVersion: v2
name: sbomer-platform
description: Umbrella chart for SBOMer components and Dev infrastructure
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: manifest-storage-service-chart
    version: 0.1.6
    repository: "oci://quay.io/sbomer"
  - name: sbom-service-chart
    version: 0.1.3
    repository: "oci://quay.io/sbomer"
  - name: syft-generator-chart
    version: 0.1.4
    repository: "oci://quay.io/sbomer"