{{- if .Values.global.includeApiGateway }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway
  labels:
    app: sbomer-gateway
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: nginx
          image: nginxinc/nginx-unprivileged:alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          {{- with .Values.infra.gateway.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: cache
              mountPath: /var/cache/nginx
            - name: run
              mountPath: /var/run
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-gateway-config
        - name: cache
          emptyDir: {}
        - name: run
          emptyDir: {}
{{- end }}