{{- if .Values.global.includeStatusDb }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-status-db
  labels:
    app: status-db
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: status-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: status-db
    spec:
      containers:
        - name: postgresql
          image: {{ .Values.infra.statusDb.image }}
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-status-db-secret
                  key: postgres-db-name
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-status-db-secret
                  key: postgres-username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-status-db-secret
                  key: postgres-password
          # Use ephemeral storage for local dev
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/pgsql/data
      volumes:
        - name: db-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-status-db
  labels:
    app.kubernetes.io/name: status-db
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.infra.statusDb.service.port }}
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: status-db
{{- end }}